version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=simple_blog_api
  #Express server
  simpleapi:
    depends_on:
      - postgres
    image: umasreep/simple-api:latest
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - "3000:3000"
    volumes:
      - /usr/app/node_modules
      - .:/app
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=simple_blog_api